-- ============================================================================
-- RBAC LEGADO — Control de Acceso Basado en Roles (esquema relacional)
-- SPA "Club del Dinero" (Next.js). NO modifica archivos legacy.
--
-- !! ESTE ARCHIVO ESTÁ RETIRADO. NO ES LA FUENTE DE VERDAD DEL ACCESO. !!
--
-- La fuente de verdad del control de acceso es:
--     src/lib/seguridad/capacidades.ts   (registro maestro, en el codigo)
--     src/db/seguridad_maestro.sql       (esquema y RLS de ese maestro)
--     src/db/maestro_seed.sql            (generado desde el maestro)
--
-- Este script crea un SEGUNDO sistema en tablas distintas (public.perfiles,
-- public.permisos, public.perfil_permisos, public.usuario_permisos). La app ya
-- no lee ni escribe esas tablas: capacidades.ts, accesos.ts y el store nunca
-- las mencionan. Por eso conviven sin chocar, y por eso aplicadas no cambia
-- nada del comportamiento real.
--
-- Se conserva por dos razones: (1) las tablas pueden tener datos de una
-- instalacion anterior y borrarlas seria una decision destructiva que no
-- corresponde tomar aqui; (2) este archivo tiene validacion propia en
-- pruebas/validar-rbac.mjs seccion [10].
--
-- Si alguna vez se decide eliminarlo, hay que borrar tambien las cuatro tablas
-- y revisar antes que nada ningun reporte o exportacion las use.
--
-- Ejecutar en el SQL Editor de Supabase. Idempotente: se puede correr las
-- veces que haga falta.
--
-- Sobre el RLS: el encabezado anterior de este archivo decia "RLS por defecto
-- OFF" y las policies se llamaban "RLS off legado", pero el cuerpo SI hace
-- `enable row level security`. O sea, RLS esta ENCENDIDO y las policies son
-- permisivas: el efectoPractico es el mismo que dejarlo apagado (cualquiera con
-- la llave anon entra), pero el nombre mentia. Se corrigio el nombre.
--
-- Este esquema no es una frontera de seguridad: la SPA corre con la llave anon
-- publica, asi que cualquiera con esa llave puede editar la matriz. Es una
-- herramienta de organizacion interna (que pantalla ve cada perfil), no un
-- candado. El legado funciona exactamente igual.
--
-- Si las tablas NO existen, el front usa la matriz por defecto en memoria
-- (src/lib/seguridad/permisos.ts) y todo sigue funcionando sin errores.
-- ============================================================================

-- ---------------------------------------------------------------- perfiles
create table if not exists public.perfiles (
  id          integer generated by default as identity primary key,
  nombre      text not null unique,
  descripcion text,
  creado_en   timestamptz not null default now()
);

-- ---------------------------------------------------------------- permisos
create table if not exists public.permisos (
  id          integer generated by default as identity primary key,
  clave       text not null unique,
  modulo      text not null,
  descripcion text,
  creado_en   timestamptz not null default now()
);

-- -------------------------------------------- perfil_permisos (asignación)
create table if not exists public.perfil_permisos (
  perfil_id  integer not null references public.perfiles(id) on delete cascade,
  permiso_id integer not null references public.permisos(id) on delete cascade,
  activo     boolean not null default true,
  primary key (perfil_id, permiso_id)
);

-- ------------------------------------------- usuario_permisos (individual)
-- Permisos EXTRA por usuario que se suman (nunca restan) a los del perfil.
create table if not exists public.usuario_permisos (
  usuario_id   uuid not null,
  permiso_id   integer not null references public.permisos(id) on delete cascade,
  activo       boolean not null default true,
  primary key (usuario_id, permiso_id)
);

-- asegura identidad + RLS idéntico al resto del esquema (OFF)
alter table public.perfiles          enable row level security;
alter table public.permisos          enable row level security;
alter table public.perfil_permisos   enable row level security;
alter table public.usuario_permisos  enable row level security;

-- RLS encendido + policies permisivas. El `drop policy if exists` antes de
-- cada `create policy` es lo que hace el archivo idempotente: sin el, la
-- segunda ejecucion aborta con "policy already exists" y, al estar todo el
-- archivo en una transaccion implicita, se cae TAMBIEN el seed de las tablas
-- de arriba.
drop policy if exists "anon todo (permisivo)" on public.perfiles;
drop policy if exists "anon todo (permisivo)" on public.permisos;
drop policy if exists "anon todo (permisivo)" on public.perfil_permisos;
drop policy if exists "anon todo (permisivo)" on public.usuario_permisos;
create policy "anon todo (permisivo)" on public.perfiles         for all using (true) with check (true);
create policy "anon todo (permisivo)" on public.permisos         for all using (true) with check (true);
create policy "anon todo (permisivo)" on public.perfil_permisos  for all using (true) with check (true);
create policy "anon todo (permisivo)" on public.usuario_permisos for all using (true) with check (true);

-- ------------------------------------------------------------- seed perfiles
insert into public.perfiles (id, nombre, descripcion) values
  (1, 'Admin',      'Administrador Principal: acceso total al sistema'),
  (2, 'Taquillero', 'Operador de taquilla: registra jugadas, tablas y boletos'),
  (3, 'Auditor',    'Auditoría: lectura, reportes y trazabilidad sin operar caja'),
  (4, 'Cliente',    'Cliente del hipódromo: acceso solo al Portal del Cliente (/portal)')
on conflict (id) do update set nombre = excluded.nombre, descripcion = excluded.descripcion;

-- ------------------------------------------------------------- seed permisos
insert into public.permisos (id, clave, modulo, descripcion) values
  -- módulo general
  (1,   'acceso_dashboard',      'general',       'Acceso al Dashboard / inicio'),
  -- módulo taquilla
  (10,  'ver_taquilla',          'taquilla',      'Ver módulo de taquilla'),
  (11,  'registrar_jugada',      'taquilla',      'Registrar jugadas (boleto)'),
  (12,  'anular_ticket',         'taquilla',      'Anular ticket / boleto'),
  (13,  'liquidar_carrera',      'taquilla',      'Liquidar carrera (resultados)'),
  -- módulo tablas fijas
  (20,  'ver_tablas_fijas',      'tablas',        'Ver módulo de Tablas Fijas'),
  (21,  'publicar_tabla',        'tablas',        'Publicar tablas (ensamblaje)'),
  (22,  'editar_tabla',          'tablas',        'Editar premio, valores y cupos'),
  (23,  'vender_tabla',          'tablas',        'Vender tablas (carrito/taquilla)'),
  (24,  'imprimir_tablas',       'tablas',        'Imprimir tablas publicadas'),
  (25,  'eliminar_tabla',        'tablas',        'Eliminar tabla publicada (solo la oferta de venta)'),
  -- módulo gestión de jugadas
  (30,  'gestionar_jugadas',     'gestion',       'Ver y operar Gestión de Jugadas'),
  -- módulo ejemplares y gaceta
  (40,  'ver_ejemplares',        'ejemplares',    'Ver ejemplares y gaceta'),
  (41,  'administrar_ejemplares','ejemplares',    'Editar padrón de ejemplares'),
  -- módulo clientes
  (44,  'ver_clientes',          'clientes',      'Ver la cartera de clientes (solo lectura). Necesario para vender jugadas'),
  (45,  'gestionar_clientes',    'clientes',      'Crear, editar y borrar clientes, portal y reclamos (incluye devoluciones masivas)'),
  -- módulo contabilidad
  (50,  'ver_contabilidad',      'contabilidad',  'Ver módulo de contabilidad'),
  (51,  'registrar_ingresos',    'contabilidad',  'Registrar ingresos / avales'),
  (52,  'autorizar_pagos',       'contabilidad',  'Autorizar pagos y cierres'),
  -- módulo seguridad
  (60,  'administrar_seguridad', 'seguridad',     'Administrar perfiles y accesos'),
  (61,  'ver_auditoria',         'seguridad',     'Ver trazabilidad / auditoría'),
  -- módulo portal del cliente
  (70,  'acceso_portal',         'portal',        'Acceso al Portal del Cliente')
on conflict (id) do update set clave = excluded.clave, modulo = excluded.modulo, descripcion = excluded.descripcion;

-- ------------------------------------------------- seed perfil <> permisos
insert into public.perfil_permisos (perfil_id, permiso_id, activo) values
  -- Admin: TODO
  (1, 1, true), (1, 10, true), (1, 11, true), (1, 12, true), (1, 13, true),
  (1, 20, true), (1, 21, true), (1, 22, true), (1, 23, true), (1, 24, true),
  (1, 30, true), (1, 40, true), (1, 41, true), (1, 44, true), (1, 45, true),
  (1, 50, true), (1, 51, true), (1, 52, true),
  (1, 60, true), (1, 61, true), (1, 70, true),
  -- Taquillero: operar taquilla y tablas + ver la cartera (solo lectura)
  (2, 1, true), (2, 10, true), (2, 11, true), (2, 13, true),
  (2, 20, true), (2, 23, true), (2, 24, true), (2, 30, true), (2, 40, true),
  (2, 44, true),
  -- Auditor: solo lectura
  (3, 1, true), (3, 10, true), (3, 20, true), (3, 30, true),
  (3, 40, true), (3, 44, true), (3, 50, true), (3, 61, true),
  -- Cliente: SOLO el portal (no debe tocar el Dashboard administrativo)
  (4, 70, true)
on conflict (perfil_id, permiso_id) do update set activo = excluded.activo;

-- ============================================================================
-- Nota realtime (si se desea multi-sesión para la matriz de seguridad):
--   alter publication supabase_realtime add table public.perfil_permisos;
--   alter publication supabase_realtime add table public.permisos;
-- ============================================================================