-- ============================================================================
-- MÓDULO MAESTRO DE SEGURIDAD — esquema relacional (idempotente)
-- Ejecutar en el SQL Editor de Supabase. Se puede correr las veces que haga
-- falta. NO modifica archivos legacy.
--
-- Este esquema es el sostén del MAESTRO: el registro de capacidades vive en
-- el código (src/lib/seguridad/capacidades.ts) y acá queda el almacenamiento de
-- "quién puede qué".
--
--   capacidad              → una fila por capacidad del registro maestro
--   tipo_usuario           → los tipos: admin, operador, consulta, jugador, y
--                            los que se creen nuevos desde el módulo
--   tipo_usuario_capacidad → la MATRIZ: qué tipo tiene qué capacidad
--   usuario_sistema        → quién usa el sistema y con qué tipo
--   usuario_capacidad      → excepciones individuales (permitido/denegado)
--
-- NOTA SOBRE EL RLS: antes esta sección era "RLS encendido + policies
-- permisivas" (`for all using (true) with check (true)` para anon). Con la RLS
-- así, la llave ANON —que va incrustada en el bundle de JavaScript y lee
-- cualquiera que abra devtools— podía editar la matriz, ascenderse a admin y
-- desactivar al dueño. Las guardas del cliente no frenan eso: se saltan
-- llamando a la API. Ahora las policies deciden en Postgres con `auth.uid()`.
--
-- Si tocás este bloque, dos reglas de pruebas/validar-rbac.mjs fallan: no puede
-- haber ninguna policy para `anon` ni ninguna `using (true) with check (true)`
-- sobre estas tablas. No las comentes para "probar rápido": es exactamente el
-- estado que las hace inútiles.
-- ============================================================================

-- ------------------------------------------------------------- capacidad
-- El `clave` es el identificador estable que usa el código. No se renombra: si
-- cambia, hay que migrar la matriz.
create table if not exists public.capacidad (
  id          integer generated by default as identity primary key,
  clave       text not null unique,
  modulo      text not null,
  tipo        text not null check (tipo in ('ruta','boton','modal','celda','campo','funcion')),
  titulo      text,
  riesgo      text check (riesgo in ('lectura','escritura','critico')),
  fuente      text,
  requiere    text[] not null default '{}',
  creado_en   timestamptz not null default now()
);

-- ---------------------------------------------------------- tipo_usuario
create table if not exists public.tipo_usuario (
  id          integer generated by default as identity primary key,
  nombre      text not null unique,
  descripcion text,
  activo      boolean not null default true,
  creado_en   timestamptz not null default now()
);

-- ------------------------------------------------- tipo_usuario_capacidad
-- La matriz. `decision` es tri-estado a propósito:
--   permitido → el tipo lo tiene
--   denegado  → el tipo NO lo tiene (gana sobre lo heredado)
--   heredado  → que lo resuelva el tipo padre / la ausencia de fila
create table if not exists public.tipo_usuario_capacidad (
  tipo_usuario_id integer not null references public.tipo_usuario(id) on delete cascade,
  capacidad_id    integer not null references public.capacidad(id) on delete cascade,
  decision        text not null default 'permitido' check (decision in ('permitido','denegado','heredado')),
  primary key (tipo_usuario_id, capacidad_id)
);

-- --------------------------------------------------------- usuario_sistema
-- `id` es el identificador con el que se inicia sesión (el correo o el usuario
-- corto). `es_principal` marca al dueño del sistema: acceso total.
create table if not exists public.usuario_sistema (
  id              text primary key,
  nombre          text,
  tipo_usuario_id integer not null references public.tipo_usuario(id),
  activo          boolean not null default true,
  es_principal    boolean not null default false,
  creado_en       timestamptz not null default now()
);

-- ------------------------------------------------------ usuario_capacidad
-- Excepciones individuales por encima de la base del tipo.
create table if not exists public.usuario_capacidad (
  usuario_id   text not null,
  capacidad_id integer not null references public.capacidad(id) on delete cascade,
  decision     text not null check (decision in ('permitido','denegado')),
  primary key (usuario_id, capacidad_id)
);

-- ------------------------------------------------------- enlace con Supabase Auth
-- `usuario_sistema.id` es texto (el correo o el usuario corto) porque es lo que
-- se escribe a mano. A Postgres le sirve, pero `auth.uid()` es un uuid y no se
-- puede comparar con texto: sin esta columna, NINGUNA policy puede atar una
-- petición a una persona y todo el RLS de abajo queda inaplicable.
--
-- Es nullable a propósito: el alta por SQL (SQL Editor, service_role) no pasa
-- por acá, así que un usuario puede existir en `usuario_sistema` antes de que
-- se le cree la cuenta de Auth. Sin `auth_id` no tiene permisos: denied.
alter table public.usuario_sistema add column if not exists auth_id uuid;
create unique index if not exists usuario_sistema_auth_id_uq
  on public.usuario_sistema (auth_id) where auth_id is not null;

-- ------------------------------------------------------------- resolutores
-- Estas dos funciones son la única puerta. Son `security definer` por una razón
-- concreta: una policy sobre `usuario_capacidad` que consulta `usuario_capacidad`
-- se llama a sí misma y Postgres la corta con "infinite recursion detected in
-- policy". Al ser `definer` las ejecuta el dueño de la tabla, que no está sujeto
-- a las policies, así que no hay recursión.
--
-- `search_path` va fijo a propósito: si no, un atacante crea un esquema con su
-- propio `tipo_usuario` y lo pone delante del search_path para que la función
-- lea su tabla en vez de la nuestra. Es el ataque clásico contra `definer`.
create or replace function public.usuario_de(u uuid)
returns public.usuario_sistema
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- Dos formas de atar la petición a una persona, y solo dos:
  --   1. `auth_id`: el uuid que devolvió Auth. Es lo que manda.
  --   2. el correo EXACTO: sirve para el arranque, cuando la fila se sembró por
  --      SQL y todavía nadie pasó el uuid. Supabase confirma el correo antes de
  --      dejar iniciar sesión, así que no es una entrada libre.
  --
  -- Lo que NO está, y no debe volver: comparar por la parte local del correo
  -- ("josorioc" == "josorioc@cualquiera.com"). Con eso, cualquiera que
  -- lograra crearse una cuenta de Auth en otro dominio se haría principal.
  select *
  from public.usuario_sistema us
  where us.auth_id = u
     or (us.activo and lower(us.id) = lower(coalesce(auth.jwt() ->> 'email', '')))
  limit 1;
$$;

-- Réplica exacta de la precedencia de src/lib/seguridad/resolver.ts:
--   1. principal           → todo
--   2. excepción individual → manda, incluso para DENEGAR lo que el tipo da
--   3. base del tipo       → lo que diga la matriz
-- (los requisitos no hacen falta acá: las cinco capacidades de gestión son
--  `critico` y no declaran `requiere`, así que no hay anillo que evaluar)
--
-- Si esta función y el resolver no coinciden, la base y la UI dan respuestas
-- distintas al mismo usuario. Si se cambia una, hay que cambiar la otra.
create or replace function public.tiene_capacidad(u uuid, clave text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with fila as (select * from public.usuario_de(u))
  select coalesce(
    -- 1. principal
    (select f.es_principal from fila f)
    -- 2. excepción individual: decide sola, y su "denegado" gana
    or coalesce((
        select case uc.decision
                 when 'permitido' then true
                 when 'denegado'  then false
               end
        from fila f
        join public.usuario_capacidad uc on uc.usuario_id = f.id
        join public.capacidad c on c.id = uc.capacidad_id
        where f.activo and c.clave = clave
        limit 1
      ), false)
    -- 3. base del tipo
    or exists (
        select 1
        from fila f
        join public.tipo_usuario tu on tu.id = f.tipo_usuario_id
        join public.tipo_usuario_capacidad tc on tc.tipo_usuario_id = tu.id
        join public.capacidad c on c.id = tc.capacidad_id
        where f.activo and tu.activo and c.clave = clave
          and coalesce(tc.decision, 'heredado') <> 'denegado'
      ),
    -- Sin fila de usuario (o `u` null) las tres ramas dan NULL; un boolean NULL
    -- hace que `if not tiene_capacidad(...)` NO dispare. Se cierra en falso.
    false
  );
$$;

-- Atajo para las policies, donde se lee mucho más claro que la función entera.
create or replace function public.soy_principal(u uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select es_principal and activo from public.usuario_de(u)), false);
$$;

-- Estas funciones leen la matriz, así que no se le dan a `anon`: sin sesión
-- verificada no hay nada que preguntar.
revoke all on function public.usuario_de(uuid)          from public, anon;
revoke all on function public.tiene_capacidad(uuid, text) from public, anon;
revoke all on function public.soy_principal(uuid)       from public, anon;
grant execute on function public.usuario_de(uuid)            to authenticated;
grant execute on function public.tiene_capacidad(uuid, text)  to authenticated;
grant execute on function public.soy_principal(uuid)          to authenticated;

-- ============================================================================
-- ABAC — atributos, reglas y atributos por usuario
-- ============================================================================
--
-- El RBAC de arriba responde "¿qué tipo de usuario es?". Estas tablas
-- responden "¿sobre qué registro, con qué valor?".
--
-- ReEjemplos reales, que con RBAC solo no se pueden expresar:
--   - un ticket ya SOLUCIONADO no se vuelve a resolver (misma capacidad,
--     distinto ESTADO del registro);
--   - un operador solo liquida el HIPÓDROMO que tiene asignado (misma
--     capacidad, distinto ATRIBUTO del usuario);
--   - hay un TOPE DE MONTO que el operador aprueba y de ahí en arriba escala
--     al admin (misma capacidad, distinto VALOR).
--
-- Réplica de src/lib/seguridad/abac.ts. Si las dos copias divergen, la base y
-- la UI dan respuestas distintas al mismo usuario: eso es peor que no tener
-- ABAC, porque el operador ve un botón habilitado que la base le va a rebotar.
-- Por eso el seed sale GENERADO del TypeScript (pruebas/generar-seed-maestro.mjs).

-- --------------------------------------------------------------- atributo
-- Catálogo de lo que se puede mirar. `origen` documenta de dónde sale el valor
-- ("registro.estado", "usuario.hipodromos"): sin eso, nadie sabe qué tiene que
-- pasarle a la función cuando aparece una regla nueva.
create table if not exists public.atributo (
  id          integer generated by default as identity primary key,
  clave       text not null unique,
  nombre      text,
  tipo        text not null check (tipo in ('texto','numero','booleano','lista')),
  descripcion text,
  origen      text
);

-- -------------------------------------------------------------- regla_abac
-- `condicion` es jsonb con {operador, valor}. Se evalúa en
-- `public.cumple_condicion()`, que es la traducción de los operadores del
-- TypeScript a Postgres. El mensaje va en la fila para que el usuario lea
-- siempre el mismo texto venga de donde venga la decisión.
create table if not exists public.regla_abac (
  id               text primary key,
  capacidad_id     integer not null references public.capacidad(id) on delete cascade,
  ambito           text not null default 'global',
  atributo_id      integer not null references public.atributo(id),
  condicion        jsonb not null default '{}'::jsonb,
  efecto           text not null check (efecto in ('denegar','permitir')),
  mensaje          text not null,
  -- Para qué está la regla. `integridad` = el registro no puede quedar en un
  -- estado imposible y le aplica a todos, principal incluido. `limite` = tope
  -- operativo, que el dueño puede levantar. La coherencia entre `clase` y
  -- `principal_exento` la verifica pruebas/auditar-base-maestro.mjs: un
  -- invariante con el dueño exento es un agujero silencioso.
  clase            text not null default 'integridad' check (clase in ('integridad','limite')),
  -- true = el usuario principal también se salta la regla. Por defecto false:
  -- los invariantes de integridad (no resolver un ticket cerrado) le afectan
  -- también al dueño. Solo los topes operativos se eximen.
  principal_exento boolean not null default false,
  riesgo           text check (riesgo in ('lectura','escritura','critico')),
  fuente           text,
  activo           boolean not null default true
);
create index if not exists regla_abac_capacidad_idx on public.regla_abac (capacidad_id);

-- -------------------------------------------------------- usuario_atributo
-- Los atributos que son del USUARIO, no del registro. Es lo que hace posible
-- "este operador trabaja estos hipódromos" sin hardcodear la lista en el
-- código: la regla usa el operador `en_atributo` y lee acá.
create table if not exists public.usuario_atributo (
  usuario_id  text not null,
  atributo_id integer not null references public.atributo(id) on delete cascade,
  valor       jsonb not null,
  primary key (usuario_id, atributo_id)
);

-- ------------------------------------------- comparación de una condición
-- Traducción de los operadores de abac.ts. Es `immutable` y sin efectos: la
-- usan tanto la función de consulta como el CHECK de abajo, y una función
-- `stable` no se puede usar en un CHECK.
-- Normaliza un texto para comparar: minusculas, sin espacios de sobra y
-- SIN TILDES. Tiene que hacer EXACTAMENTE lo mismo que el `norm()` de
-- src/lib/seguridad/abac.ts; si uno de los dos perdona un acento y el otro no,
-- la base y la UI juzguan el mismo registro de forma distinta y el operador ve
-- un boton que se apaga solo en un lado.
create or replace function public.norma_abac(txt text)
returns text
language sql
immutable
as $fn$
  select translate(lower(btrim(coalesce(txt, ''))), 'áàäâãéèëêíìïîóòöôõúùüûñç', 'aaaaaeeeeiiiiooooouuuunc');
$fn$;

revoke all on function public.norma_abac(text) from public, anon;

create or replace function public.cumple_condicion(cond jsonb, valor jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  op    text := coalesce(cond ->> 'operador', '');
  hoped jsonb := cond -> 'valor';
  n     numeric;
  lo    numeric;
  hi    numeric;
  lista text[];
  rel   text;
begin
  -- `no_vacio` y `vacio` se responden ANTES del filtro de ausente, porque
  -- justamente son las reglas que preguntan por la ausencia. Si el chequeo de
  -- "vacío = bloquea" fuera primero, una regla `vacio` nunca podría cumplirse.
  if op = 'no_vacio' then
    return true;
  elsif op = 'vacio' then
    return false;   -- ya se filtró el ausente de acá para abajo
  end if;

  -- Ausente. Un `null` o un JSON vacío NO cumple: la regla bloquea, que es
  -- el cierre por omisión del ABAC. Sin esto, un formulario que manda
  -- `monto: null` pasaría el control de topes como si fuera cero.
  if valor is null or valor = 'null'::jsonb then
    return false;
  end if;
  if jsonb_typeof(valor) = 'string' and valor #>> '{}' = '' then
    return false;
  end if;
  if jsonb_typeof(valor) = 'array' and jsonb_array_length(valor) = 0 then
    return false;
  end if;

  if op = 'entre' then
    n := (valor #>> '{}')::numeric;
    lo := (hoped ->> '0')::numeric;
    hi := (hoped ->> '1')::numeric;
    if lo is null or hi is null then
      return false;  -- regla mal declarada: no se puede evaluar, no se pasa
    end if;
    return n between lo and hi;

  elsif op = 'mayor_igual' then
    return (valor #>> '{}')::numeric >= (hoped #>> '{}')::numeric;

  elsif op = 'menor_igual' then
    return (valor #>> '{}')::numeric <= (hoped #>> '{}')::numeric;

  elsif op in ('en', 'no_en', 'igual', 'diferente') then
    -- Comparación de texto: minúsculas y sin espacios, igual que el `norm()`
    -- de abac.ts. Un "efectivo" y un "Efectivo " tienen que ser lo mismo.
    rel := public.norma_abac(valor #>> '{}');
    select coalesce(array_agg(public.norma_abac(x #>> '{}')), '{}')
      into lista
      from jsonb_array_elements(case when jsonb_typeof(hoped) = 'array' then hoped else jsonb_build_array(hoped) end) x;

    if op = 'en' then       return rel = any(lista);
    elsif op = 'no_en' then return rel <> all(lista);
    elsif op = 'igual' then return rel = any(lista);
    else                         return rel <> all(lista);
    end if;

  else
    -- `en_atributo` y cualquier operador desconocido NO se resuelven acá: el
    -- conjunto permitido viene de otro atributo del contexto, y eso lo arma
    -- `puede_contexto`. Un operador desconocido devuelve false en vez de
    -- interpretar la regla de cualquier manera.
    return false;
  end if;
end;
$$;

-- El conjunto permitido de una regla `en_atributo`: el valor de otro atributo
-- en el mismo contexto. Separado para que `puede_contexto` no se repita.
create or replace function public.atributo_del_contexto(usuario text, ctx jsonb, clave text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  -- Primero lo que trae el contexto (atributo del REGISTRO); si no está, lo
  -- del usuario. Al revés sería un agujero: el registro podría declarar sus
  -- propios hipódromos y pasar la regla.
  select coalesce(
    ctx -> clave,
    (
      select ua.valor
      from public.usuario_atributo ua
      join public.atributo a on a.id = ua.atributo_id
      where ua.usuario_id = usuario and a.clave = clave
      limit 1
    )
  );
$$;

-- ------------------------------------------------------------- evaluador
-- Réplica exacta de `evaluarAbac()`: se recorren las reglas de la capacidad
-- aplicables al tipo de la sesión y la PRIMERA que no se cumple bloquea.
-- Todas se evalúan con AND.
--
-- Devuelve jsonb y no boolean para poder devolver el motivo: una policy que
-- dice "no podés tocar esto" sin decir por qué es una demeña para el operador,
-- y hace que terminen saltándose la pantalla para entender qué pasa.
create or replace function public.evaluar_abac(u uuid, clave text, ctx jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  f       public.usuario_sistema;
  tipo    text;
  r       record;
  v       jsonb;
  cond    jsonb;
  op      text;
  conjunto text;
begin
  f := public.usuario_de(u);
  if f is null or not f.activo then
    return jsonb_build_object('permitido', false, 'motivo', 'Sin usuario de sistema o inactivo.');
  end if;

  -- El ámbito `tipo:operador` se resuelve con el NOMBRE del tipo, no con el
  -- id: el id es un identity y el seed lo escribe a mano, así que si algún día
  -- el orden cambia, las reglas de ámbito dejan de pegar con el tipo correcto
  -- sin que nada avise.
  select lower(tu.nombre) into tipo
  from public.tipo_usuario tu
  where tu.id = f.tipo_usuario_id and tu.activo;

  for r in
    select ra.id, ra.condicion, ra.mensaje, ra.ambito, ra.principal_exento, a.clave as atributo
    from public.regla_abac ra
    join public.capacidad c on c.id = ra.capacidad_id
    join public.atributo a on a.id = ra.atributo_id
    where c.clave = clave
      and ra.activo
      and (ra.ambito = 'global' or ra.ambito = 'tipo:' || tipo)
    order by ra.id
  loop
    -- El principal se exime solo de las reglas marcadas como tales.
    if f.es_principal and r.principal_exento then
      continue;
    end if;

    v := public.atributo_del_contexto(f.id, coalesce(ctx, '{}'::jsonb), r.atributo);
    cond := r.condicion;
    op := cond ->> 'operador';

    if op = 'en_atributo' then
      conjunto := cond ->> 'valor';
      -- Se resuelve el conjunto desde el contexto del USUARIO, no desde el del
      -- registro: si el registro pudiera elegir el conjunto, la regla no diría
      -- nada.
      if not public.cumple_condicion(
           jsonb_build_object('operador', 'en', 'valor', public.atributo_del_contexto(f.id, '{}'::jsonb, conjunto)),
           v
         ) then
        return jsonb_build_object('permitido', false, 'regla', r.id, 'motivo', r.mensaje);
      end if;
    else
      if not public.cumple_condicion(cond, v) then
        return jsonb_build_object('permitido', false, 'regla', r.id, 'motivo', r.mensaje);
      end if;
    end if;
  end loop;

  return jsonb_build_object('permitido', true, 'regla', null, 'motivo', null);
end;
$$;

-- Azúcar sintáctico para las policies: true/false, y el motivo aparte.
create or replace function public.puede_contexto(u uuid, clave text, ctx jsonb)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((public.evaluar_abac(u, clave, coalesce(ctx, '{}'::jsonb)) ->> 'permitido')::boolean, false);
$$;

-- El motivo, para poder mandarlo al cliente y explicar el rebote.
create or replace function public.motivo_abac(u uuid, clave text, ctx jsonb)
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.evaluar_abac(u, clave, coalesce(ctx, '{}'::jsonb)) ->> 'motivo';
$$;

-- ------------------------------------------------------------------ RLS ABAC
alter table public.atributo         enable row level security;
alter table public.regla_abac       enable row level security;
alter table public.usuario_atributo enable row level security;

-- El catálogo de atributos y las reglas no son secretos: el maestro los tiene
-- que poder pintar para que el operador entienda por qué un botón se apaga.
drop policy if exists "authenticated lee los atributos" on public.atributo;
drop policy if exists "authenticated lee las reglas" on public.regla_abac;
create policy "authenticated lee los atributos" on public.atributo
  for select to authenticated using (true);
create policy "authenticated lee las reglas" on public.regla_abac
  for select to authenticated using (true);

-- Los atributos del usuario son datos de la persona: cada uno ve los suyos y
-- quien administra seguridad ve todos.
drop policy if exists "authenticated lee sus atributos" on public.usuario_atributo;
create policy "authenticated lee sus atributos" on public.usuario_atributo
  for select to authenticated
  using (
    public.soy_principal(auth.uid())
    or public.tiene_capacidad(auth.uid(), 'seguridad:fn_personalizar_usuario')
    or public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_matriz')
    or usuario_id = coalesce((select id from public.usuario_de(auth.uid())), '')
  );

-- El catálogo y las reglas los genera el código (seed). NO se escriben desde
-- el cliente: si `regla_abac` fuera escribible, cualquiera con la llave anon
-- se agregaría una regla que le permita lo que quiera, y el ABAC se convierte
-- en un agujero en lugar de una barrera.
drop policy if exists "escribe atributos quien administra" on public.atributo;
drop policy if exists "escribe reglas quien administra" on public.regla_abac;

-- Los atributos de un usuario los asigna quien administra seguridad. Mismas
-- capacidades que las excepciones individuales (`fn_personalizar_usuario`):
-- son el mismo tipo de dato —una personalización por persona.
drop policy if exists "escribe atributos de usuario quien los personaliza" on public.usuario_atributo;
create policy "escribe atributos de usuario quien los personaliza" on public.usuario_atributo
  for all to authenticated
  using (public.tiene_capacidad(auth.uid(), 'seguridad:fn_personalizar_usuario')
      or public.soy_principal(auth.uid()))
  with check (public.tiene_capacidad(auth.uid(), 'seguridad:fn_personalizar_usuario')
            or public.soy_principal(auth.uid()));

-- Las funciones del ABAC tampoco se le dan a `anon`: sin sesión verificada no
-- hay a quién preguntarle por sus atributos.
revoke all on function public.cumple_condicion(jsonb, jsonb) from public, anon;
revoke all on function public.atributo_del_contexto(text, jsonb, text) from public, anon;
revoke all on function public.evaluar_abac(uuid, text, jsonb) from public, anon;
revoke all on function public.puede_contexto(uuid, text, jsonb) from public, anon;
revoke all on function public.motivo_abac(uuid, text, jsonb) from public, anon;
grant execute on function public.cumple_condicion(jsonb, jsonb) to authenticated;
grant execute on function public.atributo_del_contexto(text, jsonb, text) to authenticated;
grant execute on function public.evaluar_abac(uuid, text, jsonb) to authenticated;
grant execute on function public.puede_contexto(uuid, text, jsonb) to authenticated;
grant execute on function public.motivo_abac(uuid, text, jsonb) to authenticated;

-- ------------------------------------------------------------------ RLS
alter table public.capacidad              enable row level security;
alter table public.tipo_usuario           enable row level security;
alter table public.tipo_usuario_capacidad enable row level security;
alter table public.usuario_sistema        enable row level security;
alter table public.usuario_capacidad      enable row level security;

-- `anon` no aparece en ninguna policy a propósito. Con RLS encendido y sin
-- policy que lo mencione, el rol no autenticado no lee NI escribe: se le
-- denies por omisión, que es exactamente lo que queremos. La llave anon viaja
-- en el bundle de JavaScript, o sea que es pública para cualquiera que abra
-- devtools; por eso no puede decidir permisos.

-- ------------------------------------------------------ lectura
-- El catálogo (qué capacidades existen) y los tipos no son secretos: sin verlos
-- el módulo de seguridad no puede pintar nada. Leer la matriz NO es escribirla.
drop policy if exists "authenticated lee el catalogo"     on public.capacidad;
drop policy if exists "authenticated lee los tipos"        on public.tipo_usuario;
drop policy if exists "authenticated lee la matriz"        on public.tipo_usuario_capacidad;
create policy "authenticated lee el catalogo" on public.capacidad
  for select to authenticated using (true);
create policy "authenticated lee los tipos" on public.tipo_usuario
  for select to authenticated using (true);
create policy "authenticated lee la matriz" on public.tipo_usuario_capacidad
  for select to authenticated using (true);

-- El resto son datos de personas: cada uno ve lo suyo, y quien administra
-- seguridad los ve todos para poder trabajar.
drop policy if exists "authenticated lee el personal" on public.usuario_sistema;
create policy "authenticated lee el personal" on public.usuario_sistema
  for select to authenticated
  using (
    public.soy_principal(auth.uid())
    or public.tiene_capacidad(auth.uid(), 'seguridad:fn_asignar_tipo')
    or public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_matriz')
    or id = coalesce(auth.jwt() ->> 'email', '')
  );

drop policy if exists "authenticated lee las excepciones" on public.usuario_capacidad;
create policy "authenticated lee las excepciones" on public.usuario_capacidad
  for select to authenticated
  using (
    public.soy_principal(auth.uid())
    or public.tiene_capacidad(auth.uid(), 'seguridad:fn_personalizar_usuario')
    or public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_matriz')
    or usuario_id = coalesce((select id from public.usuario_de(auth.uid())), '')
  );

-- ------------------------------------------------------ escritura
-- Cada tabla se abre con la MISMA capacidad que ya exige el código antes de
-- escribirla (exigirCapacidad() en src/lib/seguridad/accesos.ts). La base no
-- inventa reglas: reinforce las mismas.

-- El catálogo NO se escribe desde el cliente. Es generado por el código y lo
-- siembra `src/db/maestro_seed.sql`; si se pudiera escribir desde el navegador,
-- cualquiera podría inventarse una capacidad y concedérsela. Con el seed
-- aplicado, idDeCapacidad() siempre encuentra la fila por SELECT y nunca
-- necesita insertar. Si agregás una capacidad al registro y no regenerás el
-- seed, el guardado de la matriz falla con un error claro: eso es preferible a
-- dejar la puerta abierta.
drop policy if exists "escribe el catalogo quien administra" on public.capacidad;

-- `fn_crear_tipo` crea el tipo y `fn_editar_tipo` lo modifica (incluye
-- activar/desactivar, que es lo que llama actualizarTipoUsuario()).
drop policy if exists "escribe tipos quien los administra" on public.tipo_usuario;
create policy "escribe tipos quien los administra" on public.tipo_usuario
  for all to authenticated
  using (public.tiene_capacidad(auth.uid(), 'seguridad:fn_crear_tipo')
      or public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_tipo'))
  with check (public.tiene_capacidad(auth.uid(), 'seguridad:fn_crear_tipo')
           or public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_tipo'));

-- La matriz la borra y reescribe guardarMatrizDeTipo(), que exige
-- `fn_editar_matriz`. `fn_crear_tipo` viene incluida porque al crear un tipo
-- se le appendean sus capacidades en la misma operación.
drop policy if exists "escribe la matriz quien la edita" on public.tipo_usuario_capacidad;
create policy "escribe la matriz quien la edita" on public.tipo_usuario_capacidad
  for all to authenticated
  using (public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_matriz')
      or public.tiene_capacidad(auth.uid(), 'seguridad:fn_crear_tipo'))
  with check (public.tiene_capacidad(auth.uid(), 'seguridad:fn_editar_matriz')
           or public.tiene_capacidad(auth.uid(), 'seguridad:fn_crear_tipo'));

-- Las excepciones individuales: `fn_personalizar_usuario`.
drop policy if exists "escribe excepciones quien las personaliza" on public.usuario_capacidad;
create policy "escribe excepciones quien las personaliza" on public.usuario_capacidad
  for all to authenticated
  using (public.tiene_capacidad(auth.uid(), 'seguridad:fn_personalizar_usuario'))
  with check (public.tiene_capacidad(auth.uid(), 'seguridad:fn_personalizar_usuario'));

-- El alta y el cambio de tipo: `fn_asignar_tipo`.
--
-- El `with check` es lo importante: impide que un administrador se promueva a sí
-- mismo. Poner `es_principal = true` en la fila que se está escribiendo exige
-- que quien escribe YA sea principal. Y tocar la fila de un principal exige
-- ser principal, así que un `fn_asignar_tipo` no puede desactivar ni degradar al
-- dueño del sistema. Sin esto, el admin más bajo de la escalera puede
-- escribirse a sí mismo como principal y ya no hay frontera que valga.
drop policy if exists "escribe el personal quien asigna tipo" on public.usuario_sistema;
create policy "escribe el personal quien asigna tipo" on public.usuario_sistema
  for all to authenticated
  using (
    (public.tiene_capacidad(auth.uid(), 'seguridad:fn_asignar_tipo')
     or public.soy_principal(auth.uid()))
    and (not es_principal or public.soy_principal(auth.uid()))
  )
  with check (
    (public.tiene_capacidad(auth.uid(), 'seguridad:fn_asignar_tipo')
     or public.soy_principal(auth.uid()))
    and (not es_principal or public.soy_principal(auth.uid()))
  );

-- --------------------------------------------------- seed tipos de usuario
insert into public.tipo_usuario (id, nombre, descripcion) values
  (1, 'admin',    'Administrador. Acceso total a todo el sistema.'),
  (2, 'operador', 'Opera la taquilla, las tablas y las jugadas del día.'),
  (3, 'consulta', 'Solo lectura. Puede ver y consultar, nunca escribir.'),
  (4, 'jugador',  'Usuario que juega. Acceso acotado a jugar y a su información.')
on conflict (id) do update set nombre = excluded.nombre, descripcion = excluded.descripcion;

-- =========================================================== FIN DEL SEED ==
-- A partir de acá NO se siembran capacidades a mano: las carga el propio módulo
-- de seguridad, una por una, con sus metadatos y su origen
-- (idDeCapacidad() en src/lib/seguridad/accesos.ts). Así el registro maestro y
-- la base no pueden quedar desincronizados.
--
-- Para cargar el catálogo completo por primera vez, corré en el navegador:
--   /seguridad → pestaña "Tipos de usuario" → "Base genérica" → "Guardar"
-- para cada tipo. Eso persiste la matriz de base desde el código.
--
-- O, si preferís sembrarlo por SQL, generá el INSERT con:
--   node pruebas/generar-seed-maestro.mjs > src/db/maestro_seed.sql
-- ============================================================================