-- ===========================================================================
-- CIERRES DE CAJA: DIA Y SEMANA POR GRUPO
-- ===========================================================================
-- QUE RESUELVE
-- Los botones "Cierre del Dia", "Cerrar Semana" y "Semanas Anteriores" del
-- Centro de Control del Grupo (/inicio) eran stubs: avisaban "En desarrollo".
-- Esta tabla es el registro que les falta.
--
-- QUE GUARDA, POR CIERRE
--   grupo_id     uuid  -> grupos_venta.id (el grupo que cerro)
--   tipo         text  -> 'DIA' | 'SEMANA'
--   fecha_inicio date  -> dia de apertura (en DIA, el mismo dia)
--   fecha_fin    date  -> dia de corte  (en DIA, el mismo dia)
--   balance      numeric -> resultado NETO de la casa en el rango, tal como lo
--                           devuelve el reporte semanal (positivo = la casa
--                           ganó; negativo = la casa pagó de más).
--   detalle      jsonb   -> el resumen del reporte al momento del cierre (dias,
--                           hipodromos, carreras, tickets, cruces), para que el
--                           histórico se lea sin volver a recalcular.
--   cerrado_por  text    -> quién lo ejecutó
--
-- POR QUE UNA TABLA Y NO UN "ESTADO" EN grupos_venta
-- El ciclo semanal de un grupo tiene MUCHOS ciclos (uno por semana) y además un
-- cierre por dia. Un par de flags en el grupo no puede representar "la semana del
-- 12 al 18 ya se cerro y la del 19 todavia no", que es exactamente lo que el
-- operador necesita ver en "Semanas Anteriores".
--
-- IDEMPOTENCIA
-- Un cierre por (grupo, tipo, rango): volver a cerrar el mismo rango ACTUALIZA el
-- balance en vez de duplicar la fila. Por eso el mismo botón sirve para
-- "reconsolidar" una semana despues de corregir una liquidacion.
--
-- LO QUE NO HACE
--   - No congela los datos: el cierre es una FOTO del balance. Corregir una
--     liquidacion y volver a cerrar actualiza el snapshot. No bloquea la
--     operatoria, porque en un hipodromo una correccion a posteriori es normal.
--   - No mueve saldos ni registra movimientos de caja: consolidar es una lectura
--     del reporte, no un pago. Quien paga es el modulo de Liquidacion.
--
-- ES IDEMPOTENTE. Aplicarlo varias veces no cambia nada.
-- Ejecutar en el SQL Editor de Supabase.
-- ===========================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1) Tabla
-- ---------------------------------------------------------------------------
create table if not exists public.cierres_jornada (
  id           bigint generated by default as identity primary key,
  grupo_id     uuid   not null references public.grupos_venta(id) on delete cascade,
  tipo         text   not null,
  fecha_inicio date   not null,
  fecha_fin    date   not null,
  balance      numeric not null default 0,
  detalle      jsonb   not null default '{}'::jsonb,
  cerrado_por  text,
  created_at   timestamptz not null default now(),
  constraint cierres_jornada_tipo   check (tipo in ('DIA', 'SEMANA')),
  constraint cierres_jornada_rango  check (fecha_fin >= fecha_inicio),
  constraint cierres_jornada_unico  unique (grupo_id, tipo, fecha_inicio, fecha_fin)
);

-- Si la tabla venia de una corrida anterior a medias, se completa lo que falte
-- en vez de fallar: el `create table if not exists` es un mentiroso cuando la
-- forma no coincide.
alter table public.cierres_jornada add column if not exists balance     numeric not null default 0;
alter table public.cierres_jornada add column if not exists detalle     jsonb   not null default '{}'::jsonb;
alter table public.cierres_jornada add column if not exists cerrado_por text;
alter table public.cierres_jornada add column if not exists created_at  timestamptz not null default now();

-- El indice unico es lo que hace idempotente el `upsert` desde la app. Si el
-- `create table` no lo dejó (tabla preexistente), se crea como indice unico,
-- que para `on conflict` es exactamente lo mismo.
create unique index if not exists cierres_jornada_unico_idx
  on public.cierres_jornada (grupo_id, tipo, fecha_inicio, fecha_fin);

create index if not exists cierres_jornada_grupo_fecha_idx
  on public.cierres_jornada (grupo_id, fecha_fin desc);

-- ---------------------------------------------------------------------------
-- 2) RLS + PERMISOS
-- El rol real de la SPA es `authenticated` (hay login real), asi que la policy
-- va a ese rol. `anon` NO lee ni escribe: el histórico de caja es información de
-- la casa.
-- ---------------------------------------------------------------------------
alter table public.cierres_jornada enable row level security;

drop policy if exists cierres_jornada_publico on public.cierres_jornada;
create policy cierres_jornada_publico on public.cierres_jornada
  for all to authenticated
  using (true) with check (true);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.cierres_jornada to authenticated, service_role;

commit;

-- ===========================================================================
-- VERIFICACION
-- 1) La tabla existe y acepta el upsert del cliente:
--      SELECT count(*) FROM public.cierres_jornada;
-- 2) RLS activo (debe dar true) y sin politica para anon:
--      select relrowsecurity from pg_class where relname = 'cierres_jornada';
--      select policyname, roles from pg_policies where tablename = 'cierres_jornada';
-- 3) Cierres del grupo, del mas nuevo al mas viejo:
--      SELECT tipo, fecha_inicio, fecha_fin, balance, cerrado_por, created_at
--        FROM public.cierres_jornada ORDER BY fecha_fin DESC, tipo;
-- ===========================================================================
